# This is a testing workflow to verify that we can pass secrets from a forked repo using the event 'pull_request_target'

name: Test secrets from fork
on:
  pull_request_target:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secrets_test:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo "print secret ${{secrets.HOST}}, ${{secrets.PASSWORD}}, ${{secrets.PORT}}, ${{secrets.PROXY_HOST}}, ${{secrets.PROXY_KEY}}, ${{secrets.PROXY_PORT}}, ${{secrets.PROXY_USERNAME}}, ${{secrets.USERNAME}}"
        
